const Router= require('express')
const router = new Router()
const bookRouter = require('./bookRouter')
const genreRouter = require('./genreRouter')
const  publisherRouter = require('./publisherRouter')
const  userRouter = require ('./userRouter')
const typeRouter = require ('./typeRouter')
const authorRouter = require('./authorRoutes')
const ageRouter=require('./ageRoutes')
const languageRouter=require('./languageRoutes')
const ratingRouter=require('./ratingRoutes')
const basketRouter=require('./bookbasketRouter')

router.use('/basket',basketRouter)
router.use('/ratings',ratingRouter)
router.use('/ages',ageRouter)
router.use('/language',languageRouter)
router.use('/user', userRouter)
router.use('/publisher', publisherRouter)
router.use('/book', bookRouter)
router.use('/genre', genreRouter)
router.use('/type',typeRouter)
router.use('/author', authorRouter)

module.exports=router;