export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/book_shop'
export const BASKET_ROUTE = '/basket'
export const BOOK_ROUTE = '/book_shop/book'
export const HOME_ROUTE = '/'